version: '3.8'

services:
  # 메인 애플리케이션
  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    container_name: report-app
    ports:
      - "${API_PORT:-7000}:7000"
    volumes:
      - ./data:/app/data:ro
      - ./reports:/app/reports:rw
      - ./static:/app/static:ro
      - ./templates:/app/templates:ro
      - ./mcp_servers:/app/mcp_servers:ro
      - /Users/lchangoo/Workspace/mcp-kr-realestate:/app/mcp_external/kr-realestate:ro
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=7000
      - VLLM_API_BASE_URL=${VLLM_API_BASE_URL}
      - VLLM_API_KEY=${VLLM_API_KEY}
      - VLLM_MODEL_NAME=${VLLM_MODEL_NAME}
      - CLAUDE_API_BASE_URL=${CLAUDE_API_BASE_URL}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - CLAUDE_MODEL_NAME=${CLAUDE_MODEL_NAME}
      - DATA_PATH=/app/data
      - REPORTS_PATH=/app/reports
      - STATIC_PATH=/app/static
      - TEMPLATES_PATH=/app/templates
      - MCP_SERVER_PATH=/app/mcp_servers
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - MAX_EXECUTION_TIME=${MAX_EXECUTION_TIME:-300}
      - MAX_CODE_SIZE=${MAX_CODE_SIZE:-10000}
      - MCP_STDIO_ENABLED=true
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    networks:
      - report-net
    restart: unless-stopped

  # Nginx 웹서버
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    container_name: report-nginx
    ports:
      - "${NGINX_PORT:-7080}:80"
    volumes:
      - ./reports:/usr/share/nginx/html/reports:ro
      - ./static:/usr/share/nginx/html/static:ro
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - report-net
    restart: unless-stopped

networks:
  report-net:
    driver: bridge

volumes:
  reports-data:
    driver: local 